/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "welcome": [],
    "quiz": [],
    "quiz.question-bank": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "courses.questions.store": [
        {
            "name": "course",
            "required": true,
            "binding": "id"
        }
    ],
    "app": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
